import { expect, type Page } from 'playwright/test'
import {
  addMessageText,
  addParallelAction,
  clickWithDialog,
  exerciseInputDelivery,
  flowBody,
  insertAfter,
  insertInside,
  insertParallelAfter,
  insertRoot,
  nodeControl,
  selectOptionContaining,
  setNodeId,
  setParallelActionId,
} from './comprehensiveMacroUiBehaviorCurrent.helpers'

export async function buildFlowControl(page: Page): Promise<void> {
  const ifNode = await insertRoot(page, 'add-flow-if', 'if_root')
  const ifBranch = ifNode.locator(':scope > [data-testid="if-branch-section"][data-flow-branch-kind="if"]')
  await ifBranch.getByTestId('condition-source').selectOption('capture_root:captured_text')
  await ifBranch.getByTestId('condition-matcher-kind').selectOption('regex')
  await ifBranch.getByTestId('condition-regex-pattern').fill('DOG_ROOT')
  await ifBranch.getByTestId('condition-regex-flags').fill('i')
  await ifBranch.getByTestId('condition-scope').selectOption('lines:any')
  await ifBranch.getByTestId('condition-matcher-kind').selectOption('simple')
  await ifBranch.getByTestId('condition-simple-op').selectOption('contains')
  await ifBranch.getByTestId('condition-simple-text').fill('DOG_ROOT')
  await ifBranch.getByTestId('condition-scope').selectOption('whole')
  await ifBranch.getByTestId('if-branch-toggle').click()
  await expect(ifBranch).toHaveClass(/collapsed/)
  await ifBranch.getByTestId('if-branch-toggle').click()

  await insertInside(flowBody(page, 'if body').last(), 'add-step-send')
  const ifSend = flowBody(page, 'if body').last().locator(':scope > [data-flow-node-type="send"]').last()
  await setNodeId(ifSend, 'send_if')
  await selectOptionContaining(ifSend.getByTestId('send-terminal'), '2 · shell')
  await addMessageText(ifSend, 'IF_MATCH')

  await ifBranch.getByTestId('add-flow-elif').click()
  let elifBranches = ifNode.locator(':scope > [data-testid="if-branch-section"][data-flow-branch-kind="elif"]')
  await expect(elifBranches).toHaveCount(1)
  await elifBranches.first().getByTestId('add-flow-elif').click()
  await expect(elifBranches).toHaveCount(2)
  await clickWithDialog(elifBranches.last().getByTestId('remove-flow-elif'), 'accept')
  await expect(elifBranches).toHaveCount(1)
  const elifBranch = elifBranches.first()
  await elifBranch.getByTestId('condition-source').selectOption('capture_root:captured_text')
  await elifBranch.getByTestId('condition-simple-text').fill('NEVER_MATCH')
  await insertInside(flowBody(page, 'elif body').last(), 'add-step-send')
  const elifSend = flowBody(page, 'elif body').last().locator(':scope > [data-flow-node-type="send"]').last()
  await setNodeId(elifSend, 'send_elif')
  await selectOptionContaining(elifSend.getByTestId('send-terminal'), '2 · shell')
  await addMessageText(elifSend, 'ELIF_MATCH')

  await elifBranch.getByTestId('add-flow-else').click()
  let elseBranch = ifNode.locator(':scope > [data-testid="if-branch-section"][data-flow-branch-kind="else"]')
  await expect(elseBranch).toHaveCount(1)
  await clickWithDialog(elseBranch.getByTestId('remove-flow-else'), 'accept')
  await expect(elseBranch).toHaveCount(0)
  await ifBranch.getByTestId('add-flow-else').click()
  elseBranch = ifNode.locator(':scope > [data-testid="if-branch-section"][data-flow-branch-kind="else"]')
  await insertInside(flowBody(page, 'else body').last(), 'add-step-send')
  const elseSend = flowBody(page, 'else body').last().locator(':scope > [data-flow-node-type="send"]').last()
  await setNodeId(elseSend, 'send_else')
  await selectOptionContaining(elseSend.getByTestId('send-terminal'), '2 · shell')
  await addMessageText(elseSend, 'ELSE_MATCH')

  const forNode = await insertRoot(page, 'add-flow-for', 'for_phases')
  await forNode.getByTestId('for-range-count').fill('2')
  await forNode.getByTestId('for-range-mode').selectOption('forever')
  await forNode.getByTestId('for-range-mode').selectOption('text-list')
  const items = forNode.getByTestId('for-text-list-item-card')
  await forNode.getByTestId('for-text-list-key').fill('phase-a')
  await forNode.getByTestId('for-text-list-value').fill('alpha')
  await items.first().getByTestId('for-text-list-item-insert-below').click()
  await forNode.getByTestId('for-text-list-key').nth(1).fill('phase-b')
  await forNode.getByTestId('for-text-list-value').nth(1).fill('beta\nsecond')
  await items.nth(1).getByTestId('for-text-list-item-insert-above').click()
  await forNode.getByTestId('for-text-list-key').nth(1).fill('temporary')
  await forNode.getByTestId('for-text-list-value').nth(1).fill('remove me')
  await items.nth(1).getByTestId('for-text-list-item-up').click()
  await items.nth(0).getByTestId('for-text-list-item-down').click()
  await items.nth(1).getByTestId('for-text-list-item-remove').click()
  await expect(forNode.getByTestId('for-text-list-item-card')).toHaveCount(2)

  await insertInside(flowBody(page, 'for body').last(), 'add-step-send')
  const loopSend = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="send"]').last()
  await setNodeId(loopSend, 'send_loop')
  await selectOptionContaining(loopSend.getByTestId('send-terminal'), '1 · shell')
  await loopSend.getByTestId('message-add-text').click()
  await loopSend.getByTestId('message-text-part').fill('LOOP ')
  await loopSend.getByTestId('message-template-toggle').check()
  await loopSend.getByTestId('message-template-insert-index').click()
  await loopSend.getByTestId('message-template-insert-key').click()
  await loopSend.getByTestId('message-template-insert-value').click()
  await expect(loopSend.getByTestId('message-text-part')).toHaveValue(/{{index}}/)

  await insertAfter(loopSend, 'add-step-notify')
  const loopNotify = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="notify"]').last()
  await setNodeId(loopNotify, 'notify_loop')
  await loopNotify.getByTestId('notify-level').selectOption('success')
  await loopNotify.getByTestId('notify-on-failure').selectOption('pause')
  await loopNotify.getByTestId('notify-on-failure').selectOption('continue')
  await loopNotify.getByTestId('notify-title').fill('Phase ')
  await loopNotify.getByTestId('notify-title-template-toggle').check()
  await loopNotify.getByTestId('notify-title-template-insert-index').click()
  await loopNotify.getByTestId('notify-title-template-insert-key').click()
  await loopNotify.getByTestId('notify-title-template-insert-value').click()
  await loopNotify.getByTestId('message-add-text').click()
  await loopNotify.getByTestId('message-text-part').fill('Notice ')
  await loopNotify.getByTestId('message-template-toggle').check()
  await loopNotify.getByTestId('message-template-insert-index').click()
  await loopNotify.getByTestId('message-template-insert-key').click()
  await loopNotify.getByTestId('message-template-insert-value').click()
  await loopNotify.getByTestId('notify-channel-system').check()
  await loopNotify.getByTestId('notify-app-toast').uncheck()
  await loopNotify.getByTestId('notify-app-toast').check()
  await loopNotify.getByTestId('notify-app-sound').selectOption('none')
  await loopNotify.getByTestId('notify-app-repeat-count').fill('2')
  await loopNotify.getByTestId('notify-app-repeat-interval-ms').fill('750')
  await loopNotify.getByTestId('notify-channel-telegram').check()
  await loopNotify.getByTestId('notify-telegram-profile').selectOption('default')
  await loopNotify.getByTestId('notify-channel-telegram').uncheck()
  await loopNotify.getByTestId('notify-channel-app').uncheck()
  await loopNotify.getByTestId('notify-channel-app').check()
  await loopNotify.getByTestId('notify-app-sound').selectOption('none')

  await insertAfter(loopNotify, 'add-step-input')
  const scopedInput = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="input"]').last()
  await setNodeId(scopedInput, 'input_scoped_temporary')
  await selectOptionContaining(scopedInput.getByTestId('input-terminal'), '1 · shell')
  await scopedInput.getByTestId('input-prompt').fill('Input ')
  await scopedInput.getByTestId('input-prompt-template-toggle').check()
  await scopedInput.getByTestId('input-prompt-template-insert-index').click()
  await scopedInput.getByTestId('input-prompt-template-insert-key').click()
  await scopedInput.getByTestId('input-prompt-template-insert-value').click()
  await scopedInput.getByTestId('input-allow-empty').check()
  await exerciseInputDelivery(scopedInput, 'input')
  await scopedInput.getByTestId('input-ending-sequence').selectOption('crlf')
  await scopedInput.getByTestId('input-default-source').selectOption('capture_root:captured_text')

  await insertAfter(scopedInput, 'add-step-wait')
  const scopedWait = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="wait"]').last()
  await setNodeId(scopedWait, 'wait_scoped_temporary')
  await scopedWait.getByTestId('wait-mode').selectOption('user-continue')
  await scopedWait.getByTestId('wait-user-continue-prompt').fill('Continue ')
  await scopedWait.getByTestId('wait-user-continue-prompt-template-toggle').check()
  await scopedWait.getByTestId('wait-user-continue-prompt-template-insert-index').click()
  await scopedWait.getByTestId('wait-user-continue-prompt-template-insert-key').click()
  await scopedWait.getByTestId('wait-user-continue-prompt-template-insert-value').click()

  await insertAfter(scopedWait, 'add-flow-break')
  const breakNode = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="break"]').last()
  await setNodeId(breakNode, 'break_temporary')
  await breakNode.getByTestId('flow-control-reason').fill('temporary break')
  await insertInside(flowBody(page, 'break action body').last(), 'add-step-send')
  await clickWithDialog(nodeControl(breakNode, 'node-remove'), 'accept')

  await nodeControl(loopNotify, 'node-add-after').click()
  await page.getByTestId('add-flow-continue').click()
  const continueNode = flowBody(page, 'for body').last().locator(':scope > [data-flow-node-type="continue"]').last()
  await setNodeId(continueNode, 'continue_temporary')
  await continueNode.getByTestId('flow-control-reason').fill('temporary continue')
  await insertInside(flowBody(page, 'continue action body').last(), 'add-step-send')
  await clickWithDialog(nodeControl(continueNode, 'node-remove'), 'accept')

  for (const temporary of [scopedInput, scopedWait]) {
    await clickWithDialog(nodeControl(temporary, 'node-remove'), 'accept')
  }
}

export async function buildParallelLanes(page: Page): Promise<void> {
  const parallel = await insertRoot(page, 'add-step-parallel', 'parallel_root')
  await parallel.getByTestId('parallel-on-lane-fail').selectOption('fail')
  await parallel.getByTestId('parallel-shared-text-order').selectOption('completion_order')
  await parallel.getByTestId('parallel-shared-text-order').selectOption('pane_order')

  await parallel.getByTestId('parallel-lane-add-empty').click()
  await page.getByTestId('parallel-lane-insertion-cancel').click()
  await parallel.getByTestId('parallel-lane-add-empty').click()
  await page.getByTestId('parallel-lane-insertion-cancel-scrim').click({ position: { x: 2, y: 2 } })

  const laneOne = parallel.getByTestId('parallel-lane-editor')
  await laneOne.getByTestId('parallel-lane-id-input').fill('lane_alpha')
  await laneOne.getByTestId('parallel-lane-label-input').fill('Alpha lane')
  await addParallelAction(laneOne, 'parallel-add-send')
  let laneAction = laneOne.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="send"]').last()
  await setParallelActionId(laneAction, 'lane_alpha_send')
  await selectOptionContaining(laneAction.getByTestId('parallel-send-terminal'), '1 · shell')
  const shellUsage = laneAction.getByTestId('parallel-terminal-usage')
  await expect(shellUsage).toContainText('Shell · owned by lane_alpha')
  await shellUsage.click()
  await expect(shellUsage.locator('..')).toContainText('cannot be selected by another pane')
  await shellUsage.click()
  await laneAction.getByTestId('message-add-text').click()
  await laneAction.getByTestId('parallel-message-text-part').fill('PARALLEL_ALPHA')
  await exerciseInputDelivery(laneAction, 'parallel-send')
  await laneAction.getByTestId('parallel-send-ending-sequence').selectOption('cr')

  await insertParallelAfter(laneAction, 'parallel-add-wait')
  laneAction = laneOne.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="wait"]').last()
  await setParallelActionId(laneAction, 'lane_alpha_wait')
  await laneAction.getByTestId('parallel-wait-duration-ms').fill('90')
  await laneAction.getByTestId('parallel-wait-mode').selectOption('terminal-quiet')
  await selectOptionContaining(laneAction.getByTestId('parallel-wait-terminal'), '1 · shell')
  await laneAction.getByTestId('parallel-wait-quiet-ms').fill('60')
  await laneAction.getByTestId('parallel-wait-max-ms').fill('1500')
  await laneAction.getByTestId('parallel-wait-on-timeout').selectOption('finish')
  await laneAction.getByTestId('parallel-wait-on-timeout').selectOption('pause')
  await laneAction.getByTestId('parallel-wait-mode').selectOption('duration')
  await laneAction.getByTestId('parallel-wait-duration-ms').fill('90')

  await insertParallelAfter(laneAction, 'parallel-add-capture')
  laneAction = laneOne.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="capture-source"]').last()
  await setParallelActionId(laneAction, 'lane_alpha_capture')
  await selectOptionContaining(laneAction.getByTestId('parallel-capture-terminal'), '1 · shell')
  await laneAction.getByTestId('parallel-capture-kind').selectOption('terminal-buffer')
  await laneAction.getByTestId('parallel-capture-mode').selectOption('raw-stream-tail')
  await laneAction.getByTestId('parallel-capture-max-chars').fill('9000')
  await laneAction.getByTestId('parallel-capture-mode').selectOption('scrollback-tail')

  await insertParallelAfter(laneAction, 'parallel-add-extract')
  laneAction = laneOne.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="extract_text"]').last()
  await setParallelActionId(laneAction, 'lane_alpha_extract')
  await laneAction.getByTestId('parallel-extract-source').selectOption('lane_alpha_capture:captured_text')
  await laneAction.getByTestId('parallel-extract-select-mode').selectOption('range')
  await laneAction.getByTestId('parallel-extract-select-mode').selectOption('all')
  await laneAction.getByTestId('parallel-extract-trim').selectOption('both')
  await laneAction.getByTestId('parallel-extract-on-empty').selectOption('fail')
  await insertParallelAfter(laneAction, 'parallel-add-send')
  const alphaSharedSend = laneOne.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="send"]').last()
  await setParallelActionId(alphaSharedSend, 'lane_alpha_to_text')
  await selectOptionContaining(alphaSharedSend.getByTestId('parallel-send-terminal'), '5 · text')
  await alphaSharedSend.getByTestId('message-add-source').click()
  await alphaSharedSend.getByTestId('message-source-part').selectOption('lane_alpha_extract:extracted_text')
  await alphaSharedSend.getByTestId('parallel-send-ending-sequence').selectOption('none')
  await expect(alphaSharedSend.getByTestId('parallel-terminal-usage')).toContainText('Exclusive Text')

  await laneOne.getByTestId('parallel-add-lane').click()
  await expect(parallel.getByTestId('parallel-lane-tab')).toHaveCount(2)
  let laneTwo = parallel.getByTestId('parallel-lane-editor')
  await laneTwo.getByTestId('parallel-lane-id-input').fill('lane_beta')
  await laneTwo.getByTestId('parallel-lane-label-input').fill('Beta lane')
  await clickWithDialog(laneTwo.getByTestId('parallel-remove-lane'), 'dismiss')
  await expect(parallel.getByTestId('parallel-lane-tab')).toHaveCount(2)
  await addParallelAction(laneTwo, 'parallel-add-send')
  laneAction = laneTwo.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="send"]').last()
  await setParallelActionId(laneAction, 'lane_beta_send')
  await expect(laneAction.getByTestId('parallel-send-terminal').locator('option[value="1"]'))
    .toHaveAttribute('disabled', '')
  await selectOptionContaining(laneAction.getByTestId('parallel-send-terminal'), '2 · shell')
  await laneAction.getByTestId('message-add-text').click()
  await laneAction.getByTestId('parallel-message-text-part').fill('PARALLEL_BETA')
  await insertParallelAfter(laneAction, 'parallel-add-wait')
  laneAction = laneTwo.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="wait"]').last()
  await setParallelActionId(laneAction, 'lane_beta_wait')
  await laneAction.getByTestId('parallel-wait-duration-ms').fill('90')
  await insertParallelAfter(laneAction, 'parallel-add-capture')
  laneAction = laneTwo.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="capture-source"]').last()
  await setParallelActionId(laneAction, 'lane_beta_capture')
  await selectOptionContaining(laneAction.getByTestId('parallel-capture-terminal'), '2 · shell')
  await insertParallelAfter(laneAction, 'parallel-add-send')
  const betaSharedSend = laneTwo.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="send"]').last()
  await setParallelActionId(betaSharedSend, 'lane_beta_to_text')
  await selectOptionContaining(betaSharedSend.getByTestId('parallel-send-terminal'), '5 · text')
  await betaSharedSend.getByTestId('message-add-source').click()
  await betaSharedSend.getByTestId('message-source-part').selectOption('lane_beta_capture:captured_text')
  await betaSharedSend.getByTestId('parallel-send-ending-sequence').selectOption('none')
  await expect(betaSharedSend.getByTestId('parallel-terminal-usage')).toContainText('Shared Text · pane order')

  await laneTwo.getByTestId('parallel-add-lane').click()
  await expect(parallel.getByTestId('parallel-lane-tab')).toHaveCount(3)
  let laneThree = parallel.getByTestId('parallel-lane-editor')
  await laneThree.getByTestId('parallel-lane-id-input').fill('lane_repair')
  await laneThree.getByTestId('parallel-lane-label-input').fill('Repair lane')
  await addParallelAction(laneThree, 'parallel-add-capture')
  laneAction = laneThree.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="capture-source"]').last()
  await setParallelActionId(laneAction, 'lane_repair_capture')
  await selectOptionContaining(laneAction.getByTestId('parallel-capture-terminal'), '4 · shell')
  await addParallelAction(laneThree, 'parallel-add-notify')
  const laneNotify = laneThree.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="notify"]').last()
  await setParallelActionId(laneNotify, 'lane_repair_notify')
  await laneNotify.getByTestId('notify-level').selectOption('warning')

  await parallel.getByTestId('parallel-lane-tab').filter({ hasText: 'Alpha lane' }).click()
  await expect(parallel.getByTestId('parallel-lane-editor').locator('[data-parallel-action-id="lane_alpha_to_text"]').getByTestId('parallel-terminal-usage')).toContainText('Shared Text · pane order')
  const alphaActions = parallel.getByTestId('parallel-lane-editor').getByTestId('parallel-lane-action')
  const firstAlphaAction = alphaActions.first()
  await firstAlphaAction.getByTestId('parallel-node-toggle-collapse').click()
  await firstAlphaAction.getByTestId('parallel-node-toggle-collapse').click()
  await alphaActions.nth(1).getByTestId('parallel-node-move-up').click()
  await alphaActions.first().getByTestId('parallel-node-move-down').click()
  await firstAlphaAction.getByTestId('parallel-lane-add-before').click()
  await page.getByTestId('parallel-add-send').click()
  const temporary = parallel.getByTestId('parallel-lane-editor').getByTestId('parallel-lane-action').first()
  await temporary.getByTestId('parallel-lane-add-after').click()
  await page.getByTestId('parallel-add-wait').click()
  const temporaryWait = parallel.getByTestId('parallel-lane-editor').locator('[data-testid="parallel-lane-action"][data-parallel-action-type="wait"]').first()
  await clickWithDialog(temporaryWait.getByTestId('parallel-node-remove'), 'accept')
  await clickWithDialog(temporary.getByTestId('parallel-node-remove'), 'accept')

  await parallel.getByTestId('parallel-lane-tab').filter({ hasText: 'Repair lane' }).click()
  laneThree = parallel.getByTestId('parallel-lane-editor')
  await clickWithDialog(laneThree.getByTestId('parallel-remove-lane'), 'accept')
  await expect(parallel.getByTestId('parallel-lane-tab')).toHaveCount(2)
  await parallel.getByTestId('parallel-add-lane').click()
  laneThree = parallel.getByTestId('parallel-lane-editor')
  await laneThree.getByTestId('parallel-lane-id-input').fill('lane_repair')
  await laneThree.getByTestId('parallel-lane-label-input').fill('Repair lane')
  await addParallelAction(laneThree, 'parallel-add-capture')
  laneAction = laneThree.locator('[data-testid="parallel-lane-action"][data-parallel-action-type="capture-source"]').last()
  await setParallelActionId(laneAction, 'lane_repair_capture')
  await selectOptionContaining(laneAction.getByTestId('parallel-capture-terminal'), '4 · shell')
}
