import { expect, test } from 'playwright/test'
import { readFileSync } from 'node:fs'

async function openTemplateDrawer(page: { getByTestId: (id: string) => any }) {
  await page.getByTestId('macro-template-drawer').evaluate((element: HTMLDetailsElement) => { element.open = true })
}

test('macro template workbench edits, saves, exports, imports and deletes Flow V2 templates', async ({ page, request }) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await request.post('/api/configs/macro-workbench-e2e/terminals?backend=fake')
  await request.post('/api/configs/macro-workbench-e2e/terminals?backend=fake')
  await page.goto('/?configId=macro-workbench-e2e')
  await expect(page.getByTestId('macro-panel')).toBeVisible()
  await expect(page.getByTestId('macro-sticky-head')).toBeVisible()
  expect(await page.getByTestId('macro-template-drawer').evaluate((element: HTMLDetailsElement) => element.open)).toBe(false)
  await openTemplateDrawer(page)

  await expect(page.getByTestId('terminal-tab')).toHaveCount(2)
  await expect(page.getByTestId('macro-import')).toBeEnabled()
  await expect(page.getByTestId('macro-export')).toBeDisabled()

  await page.getByTestId('terminal-tab').first().dblclick()
  await page.getByTestId('terminal-alias-input').fill('reviewer')
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('terminal-tab').first()).toHaveAttribute('data-terminal-alias', 'reviewer')

  await page.getByTestId('macro-create').click()
  await expect(page.getByTestId('macro-name')).toHaveValue('New Macro Template')
  await page.getByTestId('macro-name').fill('Review Fix Loop')
  await expect(page.getByTestId('macro-actions-palette')).toBeVisible()
  await expect(page.getByTestId('add-step-send')).toBeVisible()
  await expect(page.getByTestId('add-step-input')).toBeVisible()
  await expect(page.getByTestId('add-step-wait')).toBeVisible()
  await expect(page.getByTestId('add-step-capture')).toBeVisible()
  await expect(page.getByTestId('add-step-extract')).toBeVisible()
  await expect(page.getByTestId('add-step-parallel-send-capture')).toBeVisible()
  await expect(page.getByTestId('add-flow-if')).toBeVisible()
  await expect(page.getByTestId('add-flow-for')).toBeVisible()
  await expect(page.getByTestId('add-flow-return')).toBeVisible()
  await expect(page.getByTestId('add-step-sleep')).toHaveCount(0)
  await expect(page.getByTestId('add-step-parse')).toHaveCount(0)
  await expect(page.getByTestId('add-step-branch')).toHaveCount(0)

  const railBox = await page.getByTestId('macro-step-tool-rail').boundingBox()
  const runBox = await page.getByTestId('macro-run-card').boundingBox()
  const actionsBox = await page.getByTestId('macro-actions-palette').boundingBox()
  const stepListBox = await page.getByTestId('macro-step-list').boundingBox()
  expect(railBox).toBeTruthy()
  expect(runBox).toBeTruthy()
  expect(actionsBox).toBeTruthy()
  expect(stepListBox).toBeTruthy()
  expect(railBox!.x).toBeGreaterThan(stepListBox!.x + stepListBox!.width - 4)

  await page.getByTestId('message-text-part').first().fill('review docs only\nwith second line')
  await expect(page.getByTestId('message-text-part-line-numbers').first()).toContainText('2')
  await expect(page.getByTestId('message-add-source').first()).toBeEnabled()
  await page.getByTestId('message-add-source').first().click()
  await expect(page.getByTestId('message-source-part').first()).toHaveValue('')
  await expect(page.getByTestId('message-source-part').first().locator('option')).toHaveText(['none'])
  await page.getByTestId('message-part-row').filter({ hasText: '2. artifact' }).getByRole('button', { name: 'Remove' }).click()
  await page.getByTestId('add-step-wait').click()
  await expect(page.getByTestId('wait-mode').last()).toHaveValue('duration')
  await page.getByTestId('add-step-input').click()
  await page.getByTestId('add-step-capture').click()
  await expect(page.getByTestId('capture-step-kind').last()).toHaveValue('terminal-buffer')
  await expect(page.getByTestId('capture-terminal-buffer-mode').last()).toHaveValue('scrollback-tail')
  await page.getByTestId('capture-terminal-buffer-mode').last().selectOption('raw-stream-tail')
  await expect(page.getByTestId('capture-terminal-buffer-mode').last().locator('option[value="raw-stream-tail"]')).toHaveText('raw stream tail (debug only)')
  await page.getByTestId('add-step-extract').click()
  await expect(page.getByTestId('extract-text-source').last().locator('option')).toHaveText(['capture-source.captured_text'])
  await expect(page.getByTestId('extract-text-source').last()).not.toContainText('extract_text.extracted_text')
  await page.getByTestId('add-step-parallel-send-capture').click()
  await expect(page.getByTestId('parallel-item-wait-mode').first()).toHaveValue('terminal-quiet')
  await expect(page.getByTestId('parallel-item-wait-editor').first().getByText('return')).toHaveCount(0)
  await page.getByTestId('parallel-item-wait-mode').first().selectOption('duration')
  await expect(page.getByTestId('parallel-item-wait-mode').first()).toHaveValue('duration')
  await page.getByTestId('add-flow-if').click()
  await page.getByTestId('add-flow-elif').click()
  await page.getByTestId('add-flow-elif').click()
  await page.getByTestId('add-flow-for').click()
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Body JSON')
  await expect(page.getByTestId('flow-block-summary').filter({ hasText: 'for body' })).toBeVisible()
  await expect(page.getByTestId('block-add-break').first()).toBeVisible()
  await expect(page.getByTestId('block-add-continue').first()).toBeVisible()
  await page.getByTestId('flow-block-summary').filter({ hasText: 'for body' }).click()
  await expect(page.getByTestId('block-add-break').first()).toBeHidden()
  await page.getByTestId('flow-block-summary').filter({ hasText: 'for body' }).click()
  await expect(page.getByTestId('block-add-break').first()).toBeVisible()
  await page.getByTestId('block-add-break').first().click()
  await page.getByTestId('block-add-continue').first().click()
  await page.getByTestId('add-flow-return').click()

  await expect(page.getByTestId('macro-step-list')).toContainText('send_line')
  await expect(page.getByTestId('macro-step-list')).toContainText('input_line')
  await expect(page.getByTestId('macro-step-list')).toContainText('wait')
  await expect(page.getByTestId('macro-step-list')).toContainText('capture-source')
  await expect(page.getByTestId('macro-step-list')).toContainText('extract_text')
  await expect(page.getByTestId('macro-step-list')).toContainText('parallel_send_capture')
  await expect(page.getByTestId('macro-step-list')).toContainText('if')
  await expect(page.getByTestId('macro-step-list')).toContainText('for')
  await expect(page.getByTestId('macro-step-list')).toContainText('return')
  await expect(page.getByTestId('macro-step-list')).toContainText('break')
  await expect(page.getByTestId('macro-step-list')).toContainText('continue')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('parse')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('branch')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('sleep')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Terminal Mapping')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Capture Sources')

  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-view')).toBeVisible()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"schemaVersion": 2')
  await page.getByTestId('macro-json-copy').click()
  await expect.poll(async () => await page.evaluate(() => navigator.clipboard.readText())).toContain('"schemaVersion": 2')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"body"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"message"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"parallel_send_capture"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"return_elif"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"return_elif_2"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"steps"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"parser"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  await page.getByTestId('macro-save').click()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()

  await page.reload()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(1)
  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"Review Fix Loop"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByTestId('macro-export').click(),
  ])
  const downloadPath = await download.path()
  expect(downloadPath).toBeTruthy()
  const exported = JSON.parse(readFileSync(downloadPath!, 'utf8')) as { schemaVersion: number; body: Array<{ type: string }> }
  expect(exported.schemaVersion).toBe(2)
  expect(exported.body.map((node) => node.type)).toContain('parallel_send_capture')
  expect(JSON.stringify(exported)).not.toContain('session_id')
  expect(JSON.stringify(exported)).not.toContain('terminalAliases')
  expect(JSON.stringify(exported)).not.toContain('captureSources')
  expect(JSON.stringify(exported)).not.toContain('"steps"')

  await page.getByTestId('macro-import-file').setInputFiles(downloadPath!)
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    expect(dialog.message()).toContain('Delete macro template')
    await dialog.dismiss()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    await dialog.accept()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(1)
})
