import { expect, test } from 'playwright/test'
import { readFileSync } from 'node:fs'

async function openTemplateDrawer(page: { getByTestId: (id: string) => any }) {
  await page.getByTestId('macro-template-drawer').evaluate((element: HTMLDetailsElement) => { element.open = true })
}

test("macro template workbench creates, saves, reloads, exports, imports and guards destructive actions", async ({ page, request }) => {
  await request.post("/api/configs/macro-workbench-e2e/terminals?backend=fake")
  await request.post("/api/configs/macro-workbench-e2e/terminals?backend=fake")
  await page.goto('/?configId=macro-workbench-e2e')
  await expect(page.getByTestId('macro-panel')).toBeVisible()
  await expect(page.getByTestId('macro-sticky-head')).toBeVisible()
  expect(await page.getByTestId('macro-template-drawer').evaluate((element: HTMLDetailsElement) => element.open)).toBe(false)
  await openTemplateDrawer(page)
  const macroTitleBox = await page.locator('.macro-header h2').boundingBox()
  const templateSummaryBox = await page.getByTestId('macro-template-summary').boundingBox()
  expect(macroTitleBox).toBeTruthy()
  expect(templateSummaryBox).toBeTruthy()
  expect(Math.abs(macroTitleBox!.y - templateSummaryBox!.y)).toBeLessThanOrEqual(8)
  const templateBodyBox = await page.locator('.macro-template-drawer-body').boundingBox()
  const macroHeaderBox = await page.locator('.macro-header').boundingBox()
  const macroTabsBox = await page.locator('.macro-tabs').boundingBox()
  expect(templateBodyBox).toBeTruthy()
  expect(macroHeaderBox).toBeTruthy()
  expect(macroTabsBox).toBeTruthy()
  expect(templateBodyBox!.y).toBeGreaterThanOrEqual(templateSummaryBox!.y + templateSummaryBox!.height)
  expect(templateBodyBox!.x).toBeLessThanOrEqual(macroHeaderBox!.x + 10)
  expect(templateBodyBox!.x + templateBodyBox!.width).toBeGreaterThanOrEqual(macroHeaderBox!.x + macroHeaderBox!.width - 10)
  expect(templateBodyBox!.y + templateBodyBox!.height).toBeLessThanOrEqual(macroTabsBox!.y)
  await expect(page.getByTestId('terminal-tab')).toHaveCount(2)
  await expect(page.getByTestId('macro-run-controls')).toBeVisible()
  await expect(page.getByTestId('macro-control-start')).toBeEnabled()
  await expect(page.getByTestId('macro-control-pause')).toBeEnabled()
  await expect(page.getByTestId('macro-control-resume')).toBeEnabled()
  await expect(page.getByTestId('macro-control-stop')).toBeEnabled()
  await page.getByTestId('macro-control-start').click()
  await expect(page.getByText('Create or select a template first')).toBeVisible()
  await expect(page.getByTestId('macro-template-actions')).toContainText('Import')
  await expect(page.getByTestId('macro-template-actions')).toContainText('Export')
  await expect(page.getByTestId('macro-import')).toBeEnabled()
  await expect(page.getByTestId('macro-export')).toBeDisabled()
  await expect(page.getByTestId('macro-json-preview')).toHaveCount(0)

  await page.getByTestId('terminal-tab').first().dblclick()
  await page.getByTestId('terminal-alias-input').fill('reviewer')
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('terminal-tab').first()).toHaveAttribute('data-terminal-alias', 'reviewer')

  await page.getByTestId('macro-create').click()
  await expect(page.getByTestId('macro-name')).toHaveValue('New Macro Template')
  await expect(page.getByTestId('macro-template-actions')).toContainText('Import')
  await expect(page.getByTestId('macro-template-actions')).toContainText('Export')
  await page.getByTestId('macro-control-start').click()
  await expect(page.getByText('template has no steps')).toBeVisible()
  await page.getByTestId('macro-name').fill('Review Fix Loop')
  await expect(page.getByTestId('macro-actions-palette')).toBeVisible()
  await expect(page.getByTestId('add-step-send')).toBeVisible()
  await expect(page.getByTestId('add-step-parallel')).toBeVisible()
  await expect(page.getByTestId('macro-flow-palette')).toBeVisible()
  await expect(page.getByTestId('flow-v2-hidden-note')).toBeHidden()
  await expect(page.getByTestId('flow-v2-if')).toHaveCount(0)
  await expect(page.getByTestId('legacy-flow-panel')).toContainText('Legacy flow nodes')
  const railBox = await page.getByTestId('macro-step-tool-rail').boundingBox()
  const runBox = await page.getByTestId('macro-run-card').boundingBox()
  const runControlsBox = await page.getByTestId('macro-run-controls').boundingBox()
  const runStatusBox = await page.getByTestId('macro-run-status').boundingBox()
  const actionsBox = await page.getByTestId('macro-actions-palette').boundingBox()
  const stepListBox = await page.getByTestId('macro-step-list').boundingBox()
  expect(railBox).toBeTruthy()
  expect(runBox).toBeTruthy()
  expect(runControlsBox).toBeTruthy()
  expect(runStatusBox).toBeTruthy()
  expect(actionsBox).toBeTruthy()
  expect(stepListBox).toBeTruthy()
  expect(railBox!.x).toBeGreaterThan(stepListBox!.x + stepListBox!.width - 4)
  expect(runControlsBox!.x).toBeGreaterThan(stepListBox!.x + stepListBox!.width - 4)
  expect(runControlsBox!.y + runControlsBox!.height).toBeLessThanOrEqual(actionsBox!.y + 2)
  expect(runStatusBox!.x).toBeLessThan(railBox!.x)
  expect(runStatusBox!.y + runStatusBox!.height).toBeLessThanOrEqual(railBox!.y + 2)

  await page.getByTestId('add-step-send').click()
  await expect(page.getByTestId('send-line-terminal')).toHaveValue('alias:reviewer')
  await page.getByTestId('send-line-text').fill('review docs only')
  await page.getByTestId('add-step-sleep').click()
  await page.getByTestId('sleep-unit-amount').fill('2')
  await page.getByTestId('sleep-unit').selectOption('s')
  await expect(page.getByTestId('sleep-ms')).toHaveValue('2000')
  await page.getByTestId('sleep-unit-amount').fill('1')
  await page.getByTestId('sleep-unit').selectOption('min')
  await expect(page.getByTestId('sleep-ms')).toHaveValue('60000')
  await page.getByTestId('sleep-unit').selectOption('h')
  await expect(page.getByTestId('sleep-ms')).toHaveValue('3600000')
  await page.getByTestId('sleep-unit').selectOption('ms')
  await page.getByTestId('sleep-unit-amount').fill('2000')
  await expect(page.getByTestId('sleep-ms')).toHaveValue('2000')
  await page.getByTestId('add-step-input').click()
  await page.getByTestId('add-step-capture').click()
  await expect(page.getByTestId('capture-step-kind')).toHaveValue('terminal-buffer')
  await expect(page.getByTestId('capture-step-terminal')).toHaveValue(/^(alias|index|id):/)
  await page.getByTestId('add-step-parse').click()
  await page.getByTestId('legacy-flow-panel').locator('summary').click()
  await page.getByTestId('add-step-branch').click()
  await page.getByTestId('add-step-goto').click()
  await page.getByTestId('add-step-fail').click()
  await page.getByTestId('add-step-stop').click()

  await expect(page.getByTestId('macro-step-list')).toContainText('send_line')
  await expect(page.getByTestId('macro-step-list')).toContainText('input_line')
  await expect(page.getByTestId('macro-step-list')).toContainText('capture-source')
  await expect(page.getByTestId('macro-step-list')).toContainText('parse')
  await expect(page.getByTestId('macro-step-list')).toContainText('branch')
  await expect(page.getByTestId('macro-step-list')).toContainText('fail')
  await expect(page.getByTestId('macro-step-list')).toContainText('stop')
  await expect(page.getByTestId('macro-step-list')).toContainText('legacy if/elif/else')
  await expect(page.getByTestId('macro-step-list')).toContainText('legacy loop jump')
  await expect(page.getByTestId('parse-step-source')).toHaveValue(/^capture_source_/)
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Terminal Mapping')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Capture Sources')

  await page.getByTestId('macro-editor-main').evaluate((element: HTMLElement) => { element.scrollTop = element.scrollHeight })
  const scrolledMainBox = await page.getByTestId('macro-editor-main').boundingBox()
  const scrolledRailBox = await page.getByTestId('macro-step-tool-rail').boundingBox()
  expect(scrolledMainBox).toBeTruthy()
  expect(scrolledRailBox).toBeTruthy()
  expect(scrolledMainBox!.x + scrolledMainBox!.width).toBeLessThanOrEqual(scrolledRailBox!.x)
  expect(scrolledRailBox!.y + scrolledRailBox!.height).toBeLessThanOrEqual(scrolledMainBox!.y + scrolledMainBox!.height + 1)

  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-view')).toBeVisible()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"terminal": {')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"kind": "alias"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"value": "reviewer"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"kind": "regex"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"loopGuard"')
  await page.getByTestId('macro-tab-editor').click()
  await expect(page.getByTestId('macro-json-preview')).toHaveCount(0)
  await openTemplateDrawer(page)

  await page.getByTestId('macro-save').click()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()

  await page.reload()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(1)
  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"Review Fix Loop"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"send_line"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"input_line"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByTestId('macro-export').click(),
  ])
  const downloadPath = await download.path()
  expect(downloadPath).toBeTruthy()
  const exported = JSON.parse(readFileSync(downloadPath!, 'utf8')) as { steps: Array<{ type: string }>; session_id?: string }
  expect(exported.steps.map((step) => step.type)).toContain('branch')
  expect(JSON.stringify(exported)).not.toContain('session_id')
  expect(JSON.stringify(exported)).not.toContain('terminalAliases')
  expect(JSON.stringify(exported)).not.toContain('captureSources')

  await page.getByTestId('macro-import-file').setInputFiles(downloadPath!)
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)
  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"Review Fix Loop"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    expect(dialog.message()).toContain('Delete macro template')
    await dialog.dismiss()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    await dialog.accept()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(1)
})
