import { expect, test, type Locator, type Page } from 'playwright/test'
import { readFileSync } from 'node:fs'

const inputDeliveryHelp = 'Auto uses Bracketed paste for Shell tabs and Direct bytes for Text tabs. Direct bytes and Bracketed paste force the selected mode.'

async function openTemplateDrawer(page: { getByTestId: (id: string) => any }) {
  if (await page.getByTestId('macro-template-drawer-body').count() === 0) {
    await page.getByTestId('macro-template-drawer').click()
  }
  await expect(page.getByTestId('macro-template-drawer-body')).toBeVisible()
}

async function fieldTypography(control: any) {
  return control.evaluate((element: HTMLSelectElement) => {
    const label = element.labels?.[0]
    if (!label) throw new Error('missing field label')
    const controlStyle = getComputedStyle(element)
    const labelStyle = getComputedStyle(label)
    return {
      control: { fontFamily: controlStyle.fontFamily, fontSize: controlStyle.fontSize, fontWeight: controlStyle.fontWeight },
      label: { fontFamily: labelStyle.fontFamily, fontSize: labelStyle.fontSize, fontWeight: labelStyle.fontWeight },
    }
  })
}

function flowBody(page: Page, label: string) {
  return page.locator('[data-testid="flow-block"][data-flow-body-label="' + label + '"]')
}

function emptyBodyAdd(body: Locator) {
  return body.locator(':scope > [data-testid="empty-flow-body"] > [data-testid="empty-body-add"]')
}

async function insertionPaletteVisual(palette: Locator) {
  return await palette.evaluate((element) => {
    const style = getComputedStyle(element)
    const actions = element.querySelector('.step-actions')
    return {
      position: style.position,
      width: element.getBoundingClientRect().width,
      padding: style.padding,
      borderRadius: style.borderRadius,
      boxShadow: style.boxShadow,
      actionColumns: actions ? getComputedStyle(actions).gridTemplateColumns : '',
    }
  })
}

test('macro template workbench edits, saves, exports, imports and deletes Flow V2 templates', async ({ page, request }) => {
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await request.post('/api/configs/macro-workbench-e2e/terminals?backend=fake')
  await request.post('/api/configs/macro-workbench-e2e/terminals?backend=fake')
  await request.post('/api/configs/macro-workbench-e2e/terminals?backend=text')
  await page.goto('/?configId=macro-workbench-e2e')
  await expect(page.getByTestId('macro-panel')).toBeVisible()
  await expect(page.getByTestId('macro-sticky-head')).toBeVisible()
  await expect(page.getByTestId('macro-template-drawer-body')).toHaveCount(0)
  await openTemplateDrawer(page)

  await expect(page.getByTestId('terminal-tab')).toHaveCount(3)
  await expect(page.getByTestId('macro-import')).toBeEnabled()
  await expect(page.getByTestId('macro-export')).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('macro-template-drawer-body')).toHaveCount(0)

  await page.getByTestId('terminal-tab').first().dblclick()
  await page.getByTestId('terminal-alias-input').fill('reviewer')
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('terminal-tab').first()).toHaveAttribute('data-terminal-alias', 'reviewer')

  await openTemplateDrawer(page)
  await page.getByTestId('macro-create').click()
  await expect(page.getByTestId('macro-name')).toHaveValue('New Macro Template')
  await page.getByTestId('macro-name').fill('Review Fix Loop')
  await page.getByTestId('macro-template-summary').click()
  await expect(page.getByTestId('macro-step-tool-rail')).toHaveCount(0)
  await expect(page.getByTestId('macro-insertion-palette')).toHaveCount(0)
  await page.getByTestId('empty-body-add').first().click()
  await expect(page.getByTestId('macro-actions-palette')).toBeVisible()
  const mainPaletteVisual = await insertionPaletteVisual(page.getByTestId('macro-insertion-palette'))
  await expect(page.getByTestId('add-step-send')).toBeVisible()
  await expect(page.getByTestId('add-step-input')).toBeVisible()
  await expect(page.getByTestId('add-step-wait')).toBeVisible()
  await expect(page.getByTestId('add-step-capture')).toBeVisible()
  await expect(page.getByTestId('add-step-extract')).toBeVisible()
  await expect(page.getByTestId('add-step-parallel')).toBeVisible()
  await expect(page.getByTestId('add-flow-if')).toBeVisible()
  await expect(page.getByTestId('add-flow-for')).toBeVisible()
  await expect(page.getByTestId('add-flow-finish')).toBeVisible()
  await expect(page.getByTestId('add-step-sleep')).toHaveCount(0)
  await expect(page.getByTestId('add-step-parse')).toHaveCount(0)
  await expect(page.getByTestId('add-step-branch')).toHaveCount(0)
  await page.getByTestId('macro-insertion-cancel').click()
  await expect(page.getByTestId('macro-step-list')).not.toContainText('0 nodes')
  await expect(page.getByTestId('empty-body-add')).toBeVisible()
  await page.getByTestId('empty-body-add').first().click()
  await page.getByTestId('add-step-send').click()
  await expect(page.getByTestId('macro-validation-summary')).toHaveText('success')
  await expect(page.getByTestId('message-part-row')).toHaveCount(0)
  const sendDelivery = page.getByTestId('send-input-delivery')
  await expect(sendDelivery).toHaveValue('auto')
  await expect(sendDelivery.locator('option')).toHaveText(['Auto (recommended)', 'Direct bytes', 'Bracketed paste'])
  const sendDeliveryHelp = page.getByTestId('send-input-delivery-help')
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await sendDeliveryHelp.hover()
  await expect(page.getByRole('tooltip')).toHaveText(inputDeliveryHelp)
  await page.mouse.move(0, 0)
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await sendDeliveryHelp.focus()
  await expect(page.getByRole('tooltip')).toHaveText(inputDeliveryHelp)
  await sendDelivery.focus()
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  const sendEnding = page.getByTestId('send-ending-sequence')
  await expect(sendEnding).toHaveValue('cr')
  await expect(sendEnding.locator('option')).toHaveText(['None', 'CR (\\r)', 'LF (\\n)', 'CRLF (\\r\\n)'])
  await expect(sendEnding.locator('option[value="auto"]')).toHaveCount(0)
  expect(await fieldTypography(sendDelivery)).toEqual(await fieldTypography(sendEnding))
  await sendEnding.selectOption('lf')

  const sendTerminal = page.getByTestId('send-terminal').first()
  await expect(sendTerminal.locator('option')).toHaveCount(3)
  await expect(page.getByText('Target tab').first()).toBeVisible()
  await expect(sendTerminal.locator('option').first()).toContainText(/#1 \| reviewer \| shell/)
  await expect(sendTerminal).toHaveAttribute('title', /tab index: #1[\s\S]*alias: reviewer[\s\S]*id: term_[\s\S]*kind: shell/)
  const sendTerminalValues = await sendTerminal.locator('option').evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value))
  await sendTerminal.selectOption(sendTerminalValues[2])
  await expect(sendDelivery).toHaveValue('auto')
  await sendDelivery.selectOption('bracketed-paste')
  await sendTerminal.selectOption(sendTerminalValues[0])
  await expect(sendDelivery).toHaveValue('bracketed-paste')

  const stepListBox = await page.getByTestId('macro-step-list').boundingBox()
  expect(stepListBox).toBeTruthy()

  await page.getByTestId('message-add-text').first().click()
  await page.getByTestId('message-text-part').first().fill('review docs only\nwith second line')
  await expect(page.getByTestId('message-text-part-line-numbers').first()).toContainText('2')
  await expect(page.getByTestId('message-add-source').first()).toBeEnabled()
  await page.getByTestId('message-add-source').first().click()
  await expect(page.getByTestId('message-source-part').first()).toHaveValue('')
  await expect(page.getByTestId('message-source-part').first().locator('option')).toHaveText(['none'])
  const artifactPart = page.getByTestId('message-part-row').filter({ hasText: '2. artifact' })
  const artifactPartActions = artifactPart.locator(':scope > .step-title > .inline-actions > button')
  await expect(artifactPartActions).toHaveText(['', '', ''])
  expect(await artifactPartActions.evaluateAll((buttons) => buttons.map((button) => button.getAttribute('title')))).toEqual(['Up', 'Down', 'Remove'])
  await expect(artifactPartActions.locator('svg')).toHaveCount(3)
  await artifactPart.getByRole('button', { name: 'Remove' }).click()

  async function insertAfterLast(testId: string) {
    const buttons = page.getByTestId('node-add-after')
    await buttons.nth(await buttons.count() - 1).click()
    await expect(page.getByTestId('macro-insertion-palette')).toBeVisible()
    await page.getByTestId(testId).click()
  }

  await insertAfterLast('add-step-wait')
  await expect(page.getByTestId('wait-mode').last()).toHaveValue('duration')
  await insertAfterLast('add-step-input')
  const inputDelivery = page.getByTestId('input-input-delivery')
  await expect(inputDelivery).toHaveValue('auto')
  await expect(inputDelivery.locator('option')).toHaveText(['Auto (recommended)', 'Direct bytes', 'Bracketed paste'])
  await expect(page.getByTestId('input-ending-sequence')).toHaveValue('cr')
  await expect(page.getByTestId('input-ending-sequence').locator('option')).toHaveText(['None', 'CR (\\r)', 'LF (\\n)', 'CRLF (\\r\\n)'])
  await expect(page.getByTestId('input-ending-sequence').locator('option[value="auto"]')).toHaveCount(0)
  const inputTerminal = page.getByTestId('input-terminal')
  const inputTerminalValues = await inputTerminal.locator('option').evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value))
  await inputTerminal.selectOption(inputTerminalValues[2])
  await expect(inputDelivery).toHaveValue('auto')
  await inputDelivery.selectOption('direct')
  await inputTerminal.selectOption(inputTerminalValues[0])
  await expect(inputDelivery).toHaveValue('direct')
  await page.getByTestId('input-ending-sequence').selectOption('crlf')
  await insertAfterLast('add-step-capture')
  await expect(page.getByText('Source tab').first()).toBeVisible()
  await expect(page.getByTestId('capture-step-kind').last()).toHaveValue('terminal-buffer')
  await expect(page.getByTestId('capture-terminal-buffer-mode').last()).toHaveValue('scrollback-tail')
  await page.getByTestId('capture-terminal-buffer-mode').last().selectOption('raw-stream-tail')
  await expect(page.getByTestId('capture-terminal-buffer-mode').last().locator('option[value="raw-stream-tail"]')).toHaveText('raw stream tail (debug only)')
  await insertAfterLast('add-step-extract')
  await expect(page.getByTestId('extract-text-on-empty').last().locator('option')).toHaveText(['pause', 'continue', 'fail', 'finish'])
  await expect(page.getByTestId('extract-text-select-mode').last().locator('option')).toHaveText(['all', 'index', 'range'])
  await expect(page.getByTestId('extract-text-source').last().locator('option')).toHaveText(['capture_source.captured_text'])
  await expect(page.getByTestId('extract-text-source').last()).not.toContainText('extract_text.extracted_text')
  await page.getByTestId('extract-add-filter').last().click()
  const filterRemove = page.getByTestId('extract-filter-remove').last()
  await expect(filterRemove).toHaveText('')
  await expect(filterRemove).toHaveAttribute('title', 'Remove')
  await expect(filterRemove.locator('svg')).toHaveCount(1)
  await page.getByTestId('node-id-input').first().fill('extract_text')
  await expect(page.getByTestId('macro-id-edit-notice')).toContainText('Duplicate node id blocked: extract_text')
  await insertAfterLast('add-step-parallel')
  await expect(page.getByTestId("parallel-add-lane")).toBeVisible()
  await expect(page.getByText('Lane tab')).toBeVisible()
  await expect(page.getByTestId("parallel-lane-tab")).toHaveText(["lane_1"])
  await page.getByTestId("parallel-lane-add-before-output").click()
  await expect(page.getByTestId("parallel-lane-action-palette")).toBeVisible()
  await expect(page.getByTestId("parallel-lane-insertion-mode")).toHaveAttribute("data-placement-mode", "anchored")
  expect(await insertionPaletteVisual(page.getByTestId("parallel-lane-action-palette"))).toEqual(mainPaletteVisual)
  await expect(page.getByTestId("parallel-add-send")).toBeFocused()
  await page.getByTestId("parallel-add-send").click()
  await expect(page.getByTestId("parallel-lane-action")).toHaveCount(1)
  const parallelAction = page.getByTestId("parallel-lane-action").first()
  const parallelCollapse = parallelAction.getByTestId("parallel-node-toggle-collapse")
  const parallelActions = parallelAction.getByTestId("parallel-node-action-controls")
  await expect(parallelActions.locator("button")).toHaveCount(6)
  expect(await parallelActions.locator("button").evaluateAll((buttons) => buttons.map((button) => button.getAttribute("title")))).toEqual(["Collapse", "Move up", "Move down", "Add before", "Add after", "Remove"])
  await expect(parallelActions.locator("button")).toHaveText(["", "", "", "", "", ""])
  await expect(parallelAction.getByTestId("parallel-node-structural-actions")).toHaveCount(0)
  await expect(parallelAction.getByTestId("parallel-node-edit-actions")).toHaveCount(0)
  await expect(parallelCollapse).toHaveAttribute("title", "Collapse")
  await expect(parallelAction.getByTestId("parallel-node-move-up")).toHaveAttribute("title", "Move up")
  await expect(parallelAction.getByTestId("parallel-node-move-down")).toHaveAttribute("title", "Move down")
  await expect(parallelActions.locator("svg")).toHaveCount(6)
  await parallelCollapse.click()
  await expect(parallelAction).toHaveClass(/collapsed/)
  await expect(parallelAction.getByTestId("node-collapsed-badge")).toHaveText("Collapsed")
  await expect(parallelCollapse).toHaveAttribute("title", "Expand")
  await expect(parallelCollapse).toHaveAttribute("aria-expanded", "false")
  await parallelCollapse.click()
  await expect(parallelCollapse).toHaveAttribute("title", "Collapse")
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("auto")
  await expect(page.getByTestId("parallel-send-input-delivery").locator("option")).toHaveText(["Auto (recommended)", "Direct bytes", "Bracketed paste"])
  await expect(page.getByTestId("parallel-send-ending-sequence")).toHaveValue("cr")
  await expect(page.getByTestId("parallel-send-ending-sequence").locator("option")).toHaveText(["None", "CR (\\r)", "LF (\\n)", "CRLF (\\r\\n)"])
  await expect(page.getByTestId("parallel-send-ending-sequence").locator('option[value="auto"]')).toHaveCount(0)
  await expect(page.getByTestId("parallel-lane-output")).toBeVisible()
  await page.getByTestId("parallel-add-lane").click()
  await expect(page.getByTestId("parallel-lane-tab")).toHaveText(["lane_1", "lane_2"])
  await expect(page.getByTestId("parallel-on-lane-fail")).toHaveValue("pause")
  await page.getByTestId("parallel-on-lane-fail").selectOption("fail")
  await expect(page.getByTestId("parallel-on-lane-fail")).toHaveValue("fail")
  await page.getByTestId("parallel-lane-tab").filter({ hasText: "lane_1" }).click()
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("auto")
  const firstLaneTerminal = page.getByTestId("parallel-lane-terminal")
  const firstLaneTerminalValues = await firstLaneTerminal.locator("option").evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value))
  await firstLaneTerminal.selectOption(firstLaneTerminalValues[2])
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("auto")
  await firstLaneTerminal.selectOption(firstLaneTerminalValues[0])
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("auto")
  await expect(page.getByTestId("parallel-lane-terminal").locator("option").filter({ hasText: /shell_2/ })).toHaveAttribute("disabled", "")
  page.once("dialog", async (dialog) => {
    expect(dialog.message()).toContain("Remove parallel lane lane_1")
    await dialog.accept()
  })
  await page.getByTestId("parallel-remove-lane").click()
  await expect(page.getByTestId("parallel-lane-tab")).toHaveText(["lane_2"])
  await page.getByTestId("parallel-add-lane").click()
  await expect(page.getByTestId("parallel-lane-tab")).toHaveText(["lane_2", "lane_3"])
  await page.getByTestId("parallel-lane-id-input").fill("lane_2")
  await expect(page.getByTestId("parallel-id-edit-notice")).toContainText("Duplicate lane id blocked: lane_2")
  await expect(page.getByTestId("parallel-lane-id-input")).toHaveValue("lane_3")
  await page.getByTestId("parallel-lane-label-input").fill("lane_2")
  await expect(page.getByTestId("parallel-id-edit-notice")).toContainText("Duplicate lane label blocked: lane_2")
  await expect(page.getByTestId("parallel-lane-label-input")).toHaveValue("lane_3")
  await page.getByTestId("parallel-lane-add-before-output").click()
  await page.getByTestId("parallel-add-send").click()
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("auto")
  await page.getByTestId("parallel-send-input-delivery").selectOption("bracketed-paste")
  const thirdLaneTerminal = page.getByTestId("parallel-lane-terminal")
  const thirdLaneTerminalValues = await thirdLaneTerminal.locator("option").evaluateAll((options) => options.map((option) => (option as HTMLOptionElement).value))
  await thirdLaneTerminal.selectOption(thirdLaneTerminalValues[2])
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("bracketed-paste")
  await expect(page.getByTestId("parallel-send-ending-sequence")).toHaveValue("cr")
  await page.getByTestId("parallel-send-ending-sequence").selectOption("none")
  await page.getByTestId("parallel-lane-tab").filter({ hasText: "lane_2" }).click()
  await page.getByTestId("parallel-lane-tab").filter({ hasText: "lane_3" }).click()
  await expect(page.getByTestId("parallel-send-input-delivery")).toHaveValue("bracketed-paste")
  await page.getByTestId("parallel-action-id-input").fill("capture_source")
  await expect(page.getByTestId("parallel-id-edit-notice")).toContainText("Duplicate action id blocked: capture_source")
  await page.getByTestId("parallel-output-id-input").fill("capture_source")
  await expect(page.getByTestId("parallel-id-edit-notice")).toContainText("Duplicate output id blocked: capture_source")
  await insertAfterLast('add-flow-if')
  const workbenchIfBody = flowBody(page, 'if body').last()
  await emptyBodyAdd(workbenchIfBody).click()
  await page.getByTestId('add-flow-finish').click()
  await workbenchIfBody.locator('..').getByTestId('add-flow-elif').click()
  await emptyBodyAdd(flowBody(page, 'elif body').last()).click()
  await page.getByTestId('add-flow-finish').click()
  await insertAfterLast('add-flow-for')
  const forBody = flowBody(page, 'for body').last()
  await expect(forBody).toBeVisible()
  await expect(page.getByTestId('flow-block-summary')).toHaveCount(0)
  await emptyBodyAdd(forBody).click()
  await expect(page.getByTestId('add-flow-break')).toBeVisible()
  await expect(page.getByTestId('add-flow-continue')).toBeVisible()
  await page.getByTestId('add-flow-break').click()
  await forBody.locator(':scope > .flow-node-editor').last().getByTestId('node-add-after').click()
  await page.getByTestId('add-flow-continue').click()
  await insertAfterLast('add-flow-finish')
  await insertAfterLast('add-step-send')
  await expect(page.getByTestId('send-input-delivery').last()).toHaveValue('auto')
  await expect(page.getByTestId('send-ending-sequence').last()).toHaveValue('cr')

  await expect(page.getByTestId('macro-step-list')).not.toContainText('Body JSON')
  await expect(page.getByTestId('macro-step-list')).toContainText('send')
  await expect(page.getByTestId('macro-step-list')).toContainText('input')
  await expect(page.getByTestId('macro-step-list')).toContainText('wait')
  await expect(page.getByTestId('macro-step-list')).toContainText('capture-source')
  await expect(page.getByTestId('macro-step-list')).toContainText('extract_text')
  await expect(page.getByTestId('macro-step-list')).toContainText('parallel')
  await expect(page.getByTestId('macro-step-list')).toContainText('if')
  await expect(page.getByTestId('macro-step-list')).toContainText('for')
  await expect(page.getByTestId('macro-step-list')).toContainText('finish')
  await expect(page.getByTestId('macro-step-list')).toContainText('break')
  await expect(page.getByTestId('macro-step-list')).toContainText('continue')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('parse')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('branch')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('sleep')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Terminal Mapping')
  await expect(page.getByTestId('macro-step-list')).not.toContainText('Capture Sources')

  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-view')).toBeVisible()
  await expect.poll(async () => {
    const box = await page.getByTestId('macro-json-preview').boundingBox()
    return Math.round(box?.height ?? 0)
  }).toBeGreaterThan(300)
  await expect(page.getByTestId('macro-json-preview')).toContainText('"schemaVersion": 2')
  await page.getByTestId('macro-json-copy').click()
  await expect.poll(async () => await page.evaluate(() => navigator.clipboard.readText())).toContain('"schemaVersion": 2')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"body"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"message"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"parallel"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "auto"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "direct"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "bracketed-paste"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "lf"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "cr"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "crlf"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "none"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"enter"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"steps"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"parser"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  await page.getByTestId('macro-save').click()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()

  await page.reload()
  await openTemplateDrawer(page)
  await expect(page.getByTestId('macro-template-item')).toHaveCount(1)
  await page.getByTestId('macro-template-summary').click()
  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"Review Fix Loop"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "auto"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "direct"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "bracketed-paste"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "lf"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "cr"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "crlf"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"ending": "none"')
  await expect(page.getByTestId('macro-json-preview')).not.toContainText('"enter"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)
  await expect(page.getByTestId('send-input-delivery').first()).toHaveValue('bracketed-paste')
  await expect(page.getByTestId('send-input-delivery').last()).toHaveValue('auto')
  await expect(page.getByTestId('send-ending-sequence').first()).toHaveValue('lf')
  await expect(page.getByTestId('send-ending-sequence').last()).toHaveValue('cr')
  await expect(page.getByTestId('input-input-delivery')).toHaveValue('direct')
  await expect(page.getByTestId('input-ending-sequence')).toHaveValue('crlf')
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('macro-template-drawer-body')).toHaveCount(0)
  await page.getByTestId('parallel-lane-tab').filter({ hasText: 'lane_3' }).click()
  await expect(page.getByTestId('parallel-send-input-delivery')).toHaveValue('bracketed-paste')
  await expect(page.getByTestId('parallel-send-ending-sequence')).toHaveValue('none')
  await openTemplateDrawer(page)

  await page.getByTestId('macro-duplicate').click()
  await expect(page.getByText('Duplicated', { exact: true })).toBeVisible()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)
  await expect(page.getByTestId('macro-name')).toHaveValue('Review Fix Loop Copy')
  await page.getByTestId('macro-template-summary').click()
  await page.getByTestId('macro-tab-json').click()
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "auto"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "direct"')
  await expect(page.getByTestId('macro-json-preview')).toContainText('"delivery": "bracketed-paste"')
  await page.getByTestId('macro-tab-editor').click()
  await openTemplateDrawer(page)

  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByTestId('macro-export').click(),
  ])
  const downloadPath = await download.path()
  expect(downloadPath).toBeTruthy()
  const exported = JSON.parse(readFileSync(downloadPath!, 'utf8')) as { schemaVersion: number; body: Array<{ type: string }> }
  expect(exported.schemaVersion).toBe(2)
  expect(exported.body.map((node) => node.type)).toContain('parallel')
  expect(JSON.stringify(exported)).not.toContain('session_id')
  expect(JSON.stringify(exported)).not.toContain('terminalAliases')
  expect(JSON.stringify(exported)).not.toContain('captureSources')
  expect(JSON.stringify(exported)).not.toContain('"steps"')
  expect(JSON.stringify(exported)).not.toContain('"enter"')
  expect(JSON.stringify(exported)).toContain('"delivery":"auto"')
  expect(JSON.stringify(exported)).toContain('"delivery":"direct"')
  expect(JSON.stringify(exported)).toContain('"delivery":"bracketed-paste"')
  expect(JSON.stringify(exported)).toContain('"ending":"lf"')
  expect(JSON.stringify(exported)).toContain('"ending":"cr"')
  expect(JSON.stringify(exported)).toContain('"ending":"crlf"')
  expect(JSON.stringify(exported)).toContain('"ending":"none"')

  await page.getByTestId('macro-import-file').setInputFiles(downloadPath!)
  await expect(page.getByTestId('macro-template-item')).toHaveCount(3)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    expect(dialog.message()).toContain('Delete macro template')
    await dialog.dismiss()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(3)

  page.once('dialog', async (dialog) => {
    expect(dialog.type()).toBe('confirm')
    await dialog.accept()
  })
  await page.getByTestId('macro-delete').click()
  await expect(page.getByTestId('macro-template-item')).toHaveCount(2)
})
