export type UiControlEvidenceKind = 'clicked' | 'edited' | 'boundary' | 'excluded'

export type UiControlInventoryEntry = {
  key: string
  evidence: UiControlEvidenceKind
  changedBy?: string
  oldBehavior?: string
  newBehavior?: string
  spec?: string
  reason?: string
}

export const baseline031ASourceInteractiveControlCount = 202

export const baseline031ASourceInteractiveControlDigest = '7de9ac2946db94a2134e22539477094c04cc95caef6f44afce0738ff388fec19'

export const sourceInteractiveControlCount032 = 18

export const sourceInteractiveControlDigest032 = '08cd10d9663687281cecf5f1b2d761cd55570efafabd57bf0de9972aba8a2b2d'

export const sourceInteractiveControlCount033 = 19

export const sourceInteractiveControlDigest033 = '4ff921d1d3f120d6cffee8b2b842a9edfefcc545dedf2fec0d8080d6185afb3b'

export const sourceInteractiveControlCount034 = 175

export const sourceInteractiveControlDigest034 = 'ab466194c9bed56c5377668fcaf78e14d520a87067bac8f0d65dc413e59c4834'

export const sourceInteractiveControlCount035 = 174

export const sourceInteractiveControlDigest035 = 'c0be373c0b0c28b1ac83084b4d7bda99417c1345a0b303ebbb45283429298584'

export const sourceInteractiveControlCount038 = 199

export const sourceInteractiveControlDigest038 = '278ac0156e82120cbe483e2fb764273d28b7c21b78661c5b9a299bbd5a8e2c63'

export const baseline031ARuntimeControlIds = [
  // Workspace, settings, notices, panels, terminals.
  'macro-panel-toggle',
  'prompt-panel-toggle',
  'terminal-create-fake',
  'terminal-create-real',
  'terminal-create-text',
  'settings-button',
  'settings-close',
  'settings-dismiss-layer',
  'macro-insertion-placement-toggle',
  'notification-volume',
  'notification-success-sound-test',
  'tab-drag-toggle',
  'notice-dismiss',
  'notice-dismiss-layer',
  'terminal-tab',
  'terminal-alias-input',
  'terminal-tab-close',
  'text-box-editor',
  'text-box-copy',
  'macro-resize-handle',
  'prompt-resize-handle',

  // Prompt panel.
  'prompt-reset-width',
  'prompt-scope-filter',
  'prompt-search',
  'prompt-selector',
  'prompt-new-project',
  'prompt-new-global',
  'prompt-save',
  'prompt-copy',
  'prompt-delete',
  'prompt-edit-scope',
  'prompt-title',
  'prompt-tags',
  'prompt-body',

  // Macro template chrome and views.
  'macro-template-drawer',
  'macro-template-dismiss-layer',
  'macro-template-search',
  'macro-template-select',
  'macro-create',
  'macro-save',
  'macro-duplicate',
  'macro-import',
  'macro-import-file',
  'macro-export',
  'macro-delete',
  'macro-name',
  'macro-description',
  'macro-reset-width',
  'macro-tab-editor',
  'macro-tab-json',
  'macro-tab-trace',
  'macro-json-copy',
  'macro-edit-json',
  'macro-save-json',
  'macro-cancel-json',
  'macro-export-json',
  'macro-json-editor',
  'macro-validation-toggle',

  // Runner and Trace.
  'macro-control-start',
  'macro-control-pause-resume',
  'macro-control-stop',
  'macro-debug-toggle',
  'macro-run-refresh',
  'macro-run-input-text',
  'macro-run-input-submit',
  'run-create',
  'run-append-demo',
  'run-trace-copy',
  'run-log-debug-toggle',
  'run-log-refresh',
  'run-tab-log',
  'run-tab-ai',
  'run-list-item',
  'run-node-log-toggle',
  'run-artifact-ref',

  // Main insertion and generic node chrome.
  'empty-body-add',
  'add-step-send',
  'add-step-notify',
  'add-step-input',
  'add-step-wait',
  'add-step-capture',
  'add-step-extract',
  'add-step-parallel',
  'add-flow-if',
  'add-flow-for',
  'add-flow-finish',
  'add-flow-break',
  'add-flow-continue',
  'macro-move-existing-select',
  'macro-move-existing',
  'macro-insertion-cancel',
  'macro-insertion-cancel-scrim',
  'node-toggle-collapse',
  'node-move-up',
  'node-move-down',
  'node-add-before',
  'node-add-after',
  'node-remove',
  'node-id-input',
  'flow-control-reason',

  // Message, send, input, wait and notification actions.
  'message-add-text',
  'message-add-source',
  'message-part-up',
  'message-part-down',
  'message-part-remove',
  'message-text-part',
  'message-source-part',
  'message-template-toggle',
  'message-template-insert-index',
  'message-template-insert-key',
  'message-template-insert-value',
  'send-terminal',
  'send-input-delivery-help',
  'send-input-delivery',
  'send-ending-sequence',
  'notify-level',
  'notify-on-failure',
  'notify-title',
  'notify-title-template-toggle',
  'notify-title-template-insert-index',
  'notify-title-template-insert-key',
  'notify-title-template-insert-value',
  'notify-channel-app',
  'notify-channel-system',
  'notify-channel-telegram',
  'notify-app-toast',
  'notify-app-sound',
  'notify-telegram-profile',
  'input-terminal',
  'input-prompt',
  'input-prompt-template-toggle',
  'input-prompt-template-insert-index',
  'input-prompt-template-insert-key',
  'input-prompt-template-insert-value',
  'input-allow-empty',
  'input-input-delivery-help',
  'input-input-delivery',
  'input-ending-sequence',
  'input-default-source',
  'wait-mode',
  'wait-duration-ms',
  'wait-target-tab',
  'wait-quiet-ms',
  'wait-max-ms',
  'wait-on-timeout',
  'wait-user-continue-prompt',
  'wait-user-continue-prompt-template-toggle',
  'wait-user-continue-prompt-template-insert-index',
  'wait-user-continue-prompt-template-insert-key',
  'wait-user-continue-prompt-template-insert-value',

  // Capture and extract.
  'capture-step-terminal',
  'capture-step-kind',
  'capture-terminal-buffer-mode',
  'capture-max-chars',
  'capture-kind-repair',
  'extract-text-source',
  'extract-text-split-kind',
  'extract-text-keep-empty',
  'extract-text-split-pattern',
  'extract-text-split-flags',
  'extract-add-filter',
  'extract-filter-mode',
  'extract-filter-matcher-kind',
  'extract-filter-simple-op',
  'extract-filter-simple-text',
  'extract-filter-regex-pattern',
  'extract-filter-regex-flags',
  'extract-filter-remove',
  'extract-text-select-mode',
  'extract-text-select-index',
  'extract-text-select-start',
  'extract-text-select-end',
  'extract-text-extract-kind',
  'extract-text-trim',
  'extract-text-on-empty',
  'extract-text-regex-pattern',
  'extract-text-regex-flags',
  'extract-text-regex-group',

  // If and for.
  'condition-source',
  'condition-matcher-kind',
  'condition-simple-op',
  'condition-simple-text',
  'condition-regex-pattern',
  'condition-regex-flags',
  'condition-scope',
  'if-branch-toggle',
  'add-flow-elif',
  'add-flow-else',
  'remove-flow-elif',
  'remove-flow-else',
  'for-range-mode',
  'for-range-count',
  'for-text-list-add',
  'for-text-list-item-up',
  'for-text-list-item-down',
  'for-text-list-item-remove',
  'for-text-list-key',
  'for-text-list-value',

  // Parallel.
  'parallel-merge-separator',
  'parallel-include-empty-outputs',
  'parallel-on-lane-fail',
  'parallel-lane-tab',
  'parallel-add-lane',
  'parallel-remove-lane',
  'parallel-lane-id-input',
  'parallel-lane-label-input',
  'parallel-lane-terminal',
  'parallel-lane-insertion-cancel',
  'parallel-lane-insertion-cancel-scrim',
  'parallel-add-send',
  'parallel-add-wait',
  'parallel-add-capture',
  'parallel-add-extract',
  'parallel-node-toggle-collapse',
  'parallel-node-move-up',
  'parallel-node-move-down',
  'parallel-lane-add-before',
  'parallel-lane-add-after',
  'parallel-node-remove',
  'parallel-action-id-input',
  'parallel-message-text-part',
  'parallel-send-input-delivery-help',
  'parallel-send-input-delivery',
  'parallel-send-ending-sequence',
  'parallel-wait-mode',
  'parallel-wait-duration-ms',
  'parallel-wait-quiet-ms',
  'parallel-wait-max-ms',
  'parallel-capture-kind',
  'parallel-capture-mode',
  'parallel-capture-max-chars',
  'parallel-capture-kind-repair',
  'parallel-extract-source',
  'parallel-extract-select-mode',
  'parallel-extract-trim',
  'parallel-extract-on-empty',
  'parallel-lane-add-before-output',
  'parallel-output-id-input',
  'parallel-output-source',
] as const
